config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "sessions#new"
  
  resources :users, except: [:new]
  resources :tickets
  resources :searches

  get 'users/new'

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord

    def search_tickets
        tickets = Ticket.all

        tickets = tickets.where(["name LIKE ?", name]) if name.present?
        tickets = tickets.where(["description LIKE ?", description]) if description.present?
        tickets = tickets.where(["city LIKE ?", city]) if city.present?
        tickets = tickets.where(["important IS ?", important])

        return tickets
    end

end

app/models/status.rb
class Status < ApplicationRecord
    has_many :tickets
end

app/models/ticket.rb
class Ticket < ApplicationRecord

    belongs_to :user, optional: true
    belongs_to :status

    validates :name,
                 presence: true, 
                 length: { in: 4..20 }

    validates :description,
                 presence: true, 
                 length: { in: 4..20 }

    validates :city,
                 presence: true, 
                 length: { in: 4..20 }

                 

    def self.search(search)
        if search
            where(["name LIKE ?", "%#{search}%"])
        else
            all
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :tickets


    before_save {self.username = username.downcase}


    validates :username, 
                presence: true, 
                length: { in: 4..20 }, 
                uniqueness: { case_sensitive: false }


    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end

  def require_user
    if !(logged_in?)
        redirect_to login_path
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    before_action :require_user

    def new 
        @search = Search.new
        # @descriptions = Ticket.uniq.pluck(:description)
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end

    def show
        @search = Search.find(params[:id])
    end

    private

    def search_params
        params.require(:search).permit(:name, :description, :important, :city, :user_id, :status_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
      user = User.find_by(username: params[:session][:username].downcase)
      if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          flash[:notice] = "Welcome #{user.username}"
          redirect_to tickets_path
      else
          flash.now[:notice] = "There was something wrong with you login"
          render 'new'
      end
  end

  def destroy
      session[:user_id] = nil
      flash[:notice] = "Logged out"
      redirect_to root_path
      
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :require_user  

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(params_ticket)
    @ticket.user_id = nil
    @ticket.status_id = 1
    if @ticket.save
      redirect_to tickets_path
    else
      render 'new'
    end
  end

  def show
    
  end

  def edit
  end

  def update
    if @ticket.update(params_ticket)
        flash[:notice] = "Update a ticket"
        redirect_to tickets_path
    else
        render 'edit'
    end
  end

  def index
    @tickets = Ticket.search(params[:search])
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Deleted"
    redirect_to tickets_path
  end

  private 

    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def params_ticket
      params.require(:ticket).permit(:name, :description, :important, :city, :user_id, :status_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:index, :show, :edit, :destroy] 


def new
    @user = User.new
end

def index
    @users = User.all
end

def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome #{@user.username}, you have successfully sign up"
        redirect_to tickets_path
    else
        render 'new'
    end
end

def show
    @users = User.all
    @tickets = @user.tickets
end

def edit
end

def update
    if @user.update(user_params)
        flash[:notice] = "Update a user"
        redirect_to @user
    else
        render 'edit'
    end
end

def destroy
    @user.destroy
    redirect_to @user
end

private
    def user_params
        params.require(:user).permit(:username, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 100})
        email_address = "siema@wp.pl"
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username)
    end


    def logged_in?
        !!current_user 
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/new.html.erb
<%= render partial: "shared/form_ticket", locals: {object: @search, title: "Advanced Search", btn: "Search"} %>

app/views/searches/show.html.erb
<%= render partial: 'shared/nav' %>

<% if @search.search_tickets.empty? %>

   <section class="title">
     <h2>No records found</h2>
   </section>

<%else%> 

    <section class="title">
     <h2>Results</h2>
   </section>

    <table class="content-table">
    <thead >
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>City</th>
                <th>User</th>
                <th>Important</th>
                <th>Status</th>
                <%if current_user.admin? %>
                    <th colspan =2 >Options</th>
                <%else%>
                    <th>Options</th>
                    <th></th>
                <%end%>
            </tr>
        </thead>
        <tbody>
            <% @search.search_tickets.each do |search| %>
            <tr>
                <td><%= search.name %></td>
                <td><%= search.description %></td>
                <td><%= search.city %></td>
                 <% if search.user %>
                    <td><%= search.user.username %></td>
                <%else%>
                        <td> -- </td>   
                <%end%>
                
                <% if search.important %>
                        <td class="important_ticket"> <i class="fas fa-check"></i> </td>
                <%else%>
                        <td> -- </td>   
                <%end%>
                <td><%= search.status.name %></td>
                <%if current_user.admin? %>
                    <td><%= link_to "Done", ticket_path(search), method: :delete %></td>
                    <td><%= link_to "Edit", edit_ticket_path(search.id) %></td>
                <%else%>
                    <td><%= link_to "Done", ticket_path(search), method: :delete %></td>
                    <td></td>
                <%end%>
            </tr>
            <%end%>

        </tbody>
    </table>
<%end%>
<%= link_to "Back to tickets", tickets_path, class: "toTickets" %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="errors__box">
        <h4>Errors: </h4>
        <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li>  <%= msg %> </li>
        <%end%>
        </ul> 
    </div>
<%end%>

app/views/shared/_form_ticket.html.erb
 <section class="title">
     <h2> <%= title %></h2>
   </section>

<%= render partial: 'shared/errors', locals: {obj: object} %>

<section class="wrapper skinny-wrapper">
    <%= form_for object do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name, requrie: true, placeholder: "Name:" %>

    <br>

    <%= f.label :description %><br>
    <%= f.text_field :description, placeholder: "Description:" %>

    <br>

    <%= f.label :city %><br>
    <%= f.text_field :city,placeholder: "City:" %>
    
    <br>
    
  
    <%= f.label :important %><br>
    <%= f.check_box :important, placeholder: "True or False:" %>

    <br>
    <br>

    <%= f.submit btn, class: "button" %>
    <% end %>
</section>

<%= link_to "Back to tickets", tickets_path, class: "toTickets" %>

app/views/shared/_nav.html.erb
<nav class="navigation">
    <div class="logo">
        <h4>Company</h4>
    </div>
    <ul class="nav">
        <li><%= link_to "Home", tickets_path, class: "elem" %></li>
        <% if current_user.admin? %>
            <li><%= link_to "Admin - #{current_user.username}" , user_path(current_user.id), class: "elem" %></li>
            <%else%>
            <li><%= link_to "Account - #{current_user.username}" , user_path(current_user.id), class: "elem" %></li>
        <%end%>
        <% if current_user.admin? %>
            <li><%= link_to "Users" , users_path, class: "elem" %></li>
        <%end%>
        <li><%= link_to "Log out", logout_path, method: :delete, class: "elem" %></li>
    </ul>
</nav>

app/views/tickets/_ticket.html.erb
<table class="content-table">
    <thead>
    <tr>
        <th><%= link_to "Add new ticket", new_ticket_path, class: "btnTicket" %></th>
        <th></th>
        <th></th>
        <th></th>
        <th style="color: black;">Search by name: </th>
        <th>
            <%= form_tag(tickets_path, method: :get) do %>
                <%= text_field_tag(:search, params[:search]) %>
                <%= submit_tag ("Search") %>  
            <%end%>    
        </th>
        <th colspan = 2><%= link_to "Advanced Search", new_search_path, class: "btnTicket" %></th>
    </tr>
    </thead>
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>City</th>
            <th>User</th>
            <th>Important</th>
            <th>Status</th>
            <th colspan =2>Options</th>
        </tr>
    </thead>
    <tbody>
        <% @tickets.each do |ticket| %>
        <tr>
            <td><%= ticket.name %></td>
            <td><%= ticket.description %></td>
            <td><%= ticket.city %></td>
            <% if ticket.user %>
                    <td><%= ticket.user.username %></td>
            <%else%>
                    <td> -- </td>   
            <%end%>
            
            <% if ticket.important %>
                    <td class="important_ticket"> <i class="fas fa-check"></i> </td>
            <%else%>
                    <td> -- </td>   
            <%end%>
            <td><%= ticket.status.name %></td>
            <td><%= link_to "Done", ticket_path(ticket), method: :delete %></td>
            <td><%= link_to "Edit", edit_ticket_path(ticket.id) %></td>
        </tr>
        <%end%>

    </tbody>
</table>

app/views/tickets/edit.html.erb
<%= render partial: 'shared/errors', locals: {obj: @ticket} %>

 <section class="title">
     <h2>Update</h2>
   </section>

<section class="wrapper skinny-wrapper">
    <%= form_with model: @ticket do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name, requrie: true, placeholder: "Name:" %>

    <br>

    <%= f.label :description %><br>
    <%= f.text_field :description, placeholder: "Description:" %>

    <br>

    <%= f.label :city %><br>
    <%= f.text_field :city,placeholder: "City:" %>
    
    <br>
    
  
    <%= f.label :important %><br>
    <%= f.check_box :important, placeholder: "True or False:" %>

    <br>
    <br>
    <%= f.label "Choose a user for ticket:" %><br>
    <br>
    <%= f.select :user_id, User.all.map{ |u| [u.username, u.id] } %>
    <br>
    <br>
    <%= f.label "Status:" %><br>
    <br>
    <%= f.select :status_id, Status.all.map{|s| [s.name, s.id]}, prompt: "Status:" %>
    <br>
    <br>

    <%= f.submit "Update", class: "button" %>
    <% end %>
</section>

<%= link_to "Back to tickets", tickets_path, class: "toTickets" %>

app/views/tickets/index.html.erb
<%= render partial: "shared/nav" %>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>


<section class="title">
    <h2>Tickets</h2>
</section>

<%= render 'ticket' %>

app/views/tickets/new.html.erb
<%= render partial: "shared/form_ticket", locals: {object: @ticket, title: "Add new ticket", btn: "Add"} %>

app/views/tickets/show.html.erb
<h1>Tickets#show</h1>
<p>Find me in app/views/tickets/show.html.erb</p>

app/views/users/_form.html.erb
 <%= render partial: 'shared/errors', locals: {obj: @user} %> 



<section class="wrapper skinny-wrapper">
    <%= form_for @user do |f| %>

    <%= f.label :username %><br>
    <%= f.text_field :username, placeholder: "Username:" %>

    <br>

    <%= f.label :password %><br>
    <%= f.password_field :password, placeholder: "Password:" %>

    <br>

    <%= f.submit btn, class: "button" %>
    <% end %>
</section>

app/views/users/edit.html.erb
<%= render partial: "shared/nav" %>
<%=  render partial: "form", locals: {btn: "Update"}%>

app/views/users/index.html.erb
<%= render partial: 'shared/nav' %>

<section class="title">
     <h2>Users</h2>
</section>

<table class="content-table">
    <thead class="">
            <tr>
                <th>ID User</th>
                <th>Name</th>
                <th colspan = 2>Options</th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
            <tr>
                <td><%= user.id %></td>
                <td><%= user.username %></td>
                <td><%= link_to "Delete", user_path(user), method: :delete %></td>
                <td><%= link_to "Edit", edit_user_path(user.id) %></td>
                
            </tr>
            <%end%>

        </tbody>
 </table>

app/views/users/new.html.erb
<h1 class="title">Sign in for Company</h1>

<%= render partial: "form", locals: {btn: "Sign in"} %>

app/views/users/show.html.erb
<%= render partial: 'shared/nav' %>

<section class="title">
    <h2>Your profile: </h2>
</section>


<div class="user__table">
    <div class="box">  
        <div class="gravatar__img"><%= link_to gravatar_for(current_user, size: 150), current_user %></div>
        <h4><%= link_to current_user.username, current_user %></h4>
        <p class="count__ticket"><%= pluralize(current_user.tickets.count, "tickets") %></p>
        <% if logged_in? && (@user == current_user || current_user.admin? )%>
        <p><%= link_to "Edit profile", edit_user_path(@user) %></p>
        <%end%>
        <small> Join: <%= time_ago_in_words(current_user.created_at) %> </small>
    </div>
</div>


<section class="title">
    <h2>Your tickets: </h2>
</section>


<%= render 'tickets/ticket' %>